plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  '@mdi/react@*':
    dependencies:
      prop-types: '^15.5.7'
      react: '*'
